### ISSUE TITLE
Change template-Bridging-Header in iOS directory

### ISSUE THREAD

**Issue by panwrona** [magic-script/magic-script-cli#127]
Fix the name of the file to properly change to project's name while creating new project

**Comment by grozdanov** [comment]
Example for the error message:

```
~/MagicScript/sandbox $  magic-script init
? What is the name of your application? TestNewCLI
? What is the app ID of your application? com.mxs.testcli
? In which folder do you want to save this project? TestNewCLI
? What app type do you want? Components
? What platform do you want develop on? (Press <space> to select, <a> to toggle all, <i> to invert selection)Lumin
? Use TypeScript? No
 Start creating project for Components type, target: LUMIN 
new project name: TestNewCLI
Lumin manifest file has been updated successfully
Prepare project name and package in the project...
 Error: ENOENT: no such file or directory, rename '/home/MAGICLEAP/ngrozdanov/MagicScript/sandbox/TestNewCLI/reactnative/ios/Template-Bridging-Header.h' -> '/home/MAGICLEAP/ngrozdanov/MagicScript/sandbox/TestNewCLI/reactnative/ios/TestNewCLI-Bridging-Header.h'
    at Object.renameSync (fs.js:643:3)
    at Object.renameComponentsFiles (/home/MAGICLEAP/ngrozdanov/.nvm/versions/node/v12.14.1/lib/node_modules/magic-script-cli/lib/util.js:277:10)
    at /home/MAGICLEAP/ngrozdanov/.nvm/versions/node/v12.14.1/lib/node_modules/magic-script-cli/commands/init.js:185:14
    at processTicksAndRejections (internal/process/task_queues.js:94:5) {
  errno: -2,
  syscall: 'rename',
  code: 'ENOENT',
  path: '/home/MAGICLEAP/ngrozdanov/MagicScript/sandbox/TestNewCLI/reactnative/ios/Template-Bridging-Header.h',
  dest: '/home/MAGICLEAP/ngrozdanov/MagicScript/sandbox/TestNewCLI/reactnative/ios/TestNewCLI-Bridging-Header.h'
} 
~/MagicScript/sandbox $ 

```

**Comment by kpiascik** [comment]
We should only rename react if iOS/Android were specified
