### ISSUE TITLE
[MXSCOMP-23] magic-script run for ZI is not working

### ISSUE THREAD

**Issue by grzegorzdec** [magic-script/magic-script-cli#179]
I created a new project using `magic-script init`. After that, I built it by `magic-script build -h` and when I run `magic-script run` I see issue: 
```
error getting installed packages: Error: Command failed: mldb packages -j
error: no devices found

    at ChildProcess.exithandler (child_process.js:303:12)
    at ChildProcess.emit (events.js:315:20)
    at maybeClose (internal/child_process.js:1026:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:286:5) {
  killed: false,
  code: 1,
  signal: null,
  cmd: 'mldb packages -j'
}
Package: com.clitest is not installed.  Please install it.
```

I also tried building it by `magic-script build -h -i` with similar result. I'm able to run it by `mxs`

**Comment by grzegorzdec** [comment]
not implemented yet
